include: package:lints/recommended.yaml

analyzer:
  exclude: [build/**]
  language:
    strict-raw-types: true
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

linter:
  rules:
    - always_declare_return_types
    - cancel_subscriptions
    - close_sinks
    - one_member_abstracts
    - only_throw_errors
    - sort_child_properties_last
    - avoid_dynamic_calls
    - avoid_empty_else
    - avoid_relative_lib_imports
    - avoid_returning_null_for_future
    - avoid_types_as_parameter_names
    - avoid_web_libraries_in_flutter
    - control_flow_in_finally
    - hash_and_equals
    - diagnostic_describe_all_properties
    - empty_statements
    - invariant_booleans
    - iterable_contains_unrelated_type
    - literal_only_boolean_expressions
    - no_adjacent_strings_in_list
    - test_types_in_equals
    - throw_in_finally
    - unnecessary_statements #test
    - unsafe_html
    - use_build_context_synchronously
    - use_key_in_widget_constructors
    - always_specify_types
    - avoid_bool_literals_in_conditional_expressions
    - avoid_equals_and_hash_code_on_mutable_classes
    - avoid_escaping_inner_quotes
    - avoid_function_literals_in_foreach_calls
    - avoid_implementing_value_types
    - avoid_multiple_declarations_per_line
    - avoid_positional_boolean_parameters
    - flutter_style_todos
    - parameter_assignments
    - prefer_expression_function_bodies
    - prefer_final_locals
    - prefer_foreach
    - prefer_if_elements_to_conditional_expressions
    - sized_box_for_whitespace
    - sort_unnamed_constructors_first
    - unawaited_futures
    - unnecessary_await_in_return
    - unnecessary_nullable_for_final_variable_declarations
    - use_if_null_to_convert_nulls_to_bools
    - use_string_buffers
    - use_is_even_rather_than_modulo
    - use_named_constants