include: package:flutter_lints/flutter.yaml

analyzer:
  exclude: [
      build/**,
      lib/**.g.dart,
      lib/**.config.dart,
  ]
  language:
    strict-raw-types: true
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

linter:
  rules:
    always_declare_return_types: true
    cancel_subscriptions: true
    close_sinks: true
    one_member_abstracts: true
    only_throw_errors: true
    sort_child_properties_last: true
    avoid_dynamic_calls: true
    avoid_empty_else: true
    avoid_relative_lib_imports: true
    avoid_returning_null_for_future: true
    avoid_types_as_parameter_names: true
    avoid_web_libraries_in_flutter: true
    control_flow_in_finally: true
    hash_and_equals: true
    diagnostic_describe_all_properties: true
    empty_statements: true
    invariant_booleans: true
    iterable_contains_unrelated_type: true
    literal_only_boolean_expressions: true
    no_adjacent_strings_in_list: true
    test_types_in_equals: true
    throw_in_finally: true
    unnecessary_statements: true
    unsafe_html: true
    use_build_context_synchronously: true
    use_key_in_widget_constructors: true
    always_specify_types: true
    avoid_bool_literals_in_conditional_expressions: true
    avoid_equals_and_hash_code_on_mutable_classes: true
    avoid_escaping_inner_quotes: true
    avoid_function_literals_in_foreach_calls: true
    avoid_implementing_value_types: true
    avoid_multiple_declarations_per_line: true
    avoid_positional_boolean_parameters: true
    flutter_style_todos: true
    parameter_assignments: false
    prefer_expression_function_bodies: true
    prefer_final_locals: true
    prefer_foreach: true
    prefer_if_elements_to_conditional_expressions: true
    sized_box_for_whitespace: true
    sort_unnamed_constructors_first: true
    unawaited_futures: true
    unnecessary_await_in_return: true
    unnecessary_nullable_for_final_variable_declarations: true
    use_if_null_to_convert_nulls_to_bools: true
    use_string_buffers: true
    use_is_even_rather_than_modulo: true
    use_named_constants: true

    # Disabled
    constant_identifier_names: false